// AUTO-GENERATED by scripts/sync-personas.mjs — DO NOT EDIT
// Re-run: node scripts/sync-personas.mjs

export interface Persona {
  key: string;
  displayName: string;
  descShort: string;
  wertstrom: string;
  customerFacing: boolean;
  tags: string[];
  avatarUrl: string;
}

export const PERSONAS: Persona[] = [
  {
    "key": "bjoern",
    "displayName": "Björn Brandt",
    "descShort": "Brand-Architekt der Pommer Consulting",
    "wertstrom": "30-brand-zu-markt",
    "customerFacing": false,
    "tags": [
      "branding",
      "corporate-identity",
      "internal"
    ],
    "avatarUrl": "/personas/bjoern-default.webp"
  },
  {
    "key": "brand-guard",
    "displayName": "Brand-Guard",
    "descShort": "Cross-cutting Quality-Gate fuer Brand-Konsistenz der Pommer Agent Firm",
    "wertstrom": "30-brand-zu-markt",
    "customerFacing": false,
    "tags": [
      "quality-gate",
      "reviewer",
      "brand",
      "cross-cutting",
      "internal"
    ],
    "avatarUrl": "/personas/brand-guard-default.webp"
  },
  {
    "key": "conny",
    "displayName": "Conny",
    "descShort": "Content-Writer und Case-Study-Autorin der Pommer Consulting",
    "wertstrom": "30-brand-zu-markt",
    "customerFacing": false,
    "tags": [
      "marketing",
      "linkedin",
      "content",
      "case-study",
      "internal"
    ],
    "avatarUrl": "/personas/conny-default.webp"
  },
  {
    "key": "cora",
    "displayName": "Cora Pommer",
    "descShort": "CEO Pommer Consulting / Pommer Agent Firm — Chief-of-Staff, Wertstrom-Orchestrator",
    "wertstrom": "90-steuerung",
    "customerFacing": false,
    "tags": [
      "leadership",
      "ceo",
      "strategy",
      "synthesis",
      "orchestrator",
      "internal"
    ],
    "avatarUrl": "/personas/cora-default.webp"
  },
  {
    "key": "doku-generator",
    "displayName": "Dora",
    "descShort": "Dokumentations-Spezialist der Pommer Consulting",
    "wertstrom": "20-service-to-cash",
    "customerFacing": false,
    "tags": [
      "documentation",
      "delivery",
      "customer-handbook",
      "quality-gate",
      "internal"
    ],
    "avatarUrl": "/personas/doku-generator-default.webp"
  },
  {
    "key": "eike",
    "displayName": "Eike",
    "descShort": "Quality-Gate-Reviewer der Pommer Agent Firm",
    "wertstrom": "99-querschnitt",
    "customerFacing": false,
    "tags": [
      "quality-gate",
      "reviewer",
      "it-leiter",
      "business-summary",
      "internal"
    ],
    "avatarUrl": "/personas/eike-default.webp"
  },
  {
    "key": "ferdinand",
    "displayName": "Ferdinand",
    "descShort": "Finance-DE-Agent der Pommer Agent Firm",
    "wertstrom": "99-querschnitt",
    "customerFacing": false,
    "tags": [
      "finance-de",
      "compliance",
      "buchhaltung",
      "steuer",
      "querschnitt",
      "internal"
    ],
    "avatarUrl": "/personas/ferdinand-default.webp"
  },
  {
    "key": "helga",
    "displayName": "Helga",
    "descShort": "HR und Agent-Architektin der Pommer Agent Firm",
    "wertstrom": "40-idee-zu-skill",
    "customerFacing": false,
    "tags": [
      "hr",
      "agent-architecture",
      "onboarding",
      "enabling",
      "internal"
    ],
    "avatarUrl": "/personas/helga-default.webp"
  },
  {
    "key": "larissa",
    "displayName": "Larissa",
    "descShort": "Legal-DE-Agentin der Pommer Agent Firm",
    "wertstrom": "99-querschnitt",
    "customerFacing": false,
    "tags": [
      "legal-de",
      "compliance",
      "dsgvo",
      "vertrag",
      "querschnitt",
      "internal"
    ],
    "avatarUrl": "/personas/larissa-default.webp"
  },
  {
    "key": "lead-hunter",
    "displayName": "Lennart",
    "descShort": "Lead-Scout und Sales-Researcher fuer DACH-OT/SN/FNT-Umfeld",
    "wertstrom": "10-lead-to-cash",
    "customerFacing": false,
    "tags": [
      "sales",
      "lead-generation",
      "dach",
      "business-development",
      "internal"
    ],
    "avatarUrl": "/personas/lead-hunter-default.webp"
  },
  {
    "key": "meeting-summarizer",
    "displayName": "Mira",
    "descShort": "Protokollant und Operations-Assistent der Pommer Agent Firm",
    "wertstrom": "50-wissen-zu-antwort",
    "customerFacing": false,
    "tags": [
      "operations",
      "meeting",
      "protocol",
      "action-items",
      "internal"
    ],
    "avatarUrl": "/personas/meeting-summarizer-default.webp"
  },
  {
    "key": "mira",
    "displayName": "Mira",
    "descShort": "Customer-Knowledge-Auditorin der Pommer Consulting",
    "wertstrom": "40-idee-zu-skill",
    "customerFacing": false,
    "tags": [
      "knowledge-audit",
      "customer-onboarding",
      "rag-quality",
      "gap-analysis",
      "internal"
    ],
    "avatarUrl": "/personas/mira-default.webp"
  },
  {
    "key": "ot-expert",
    "displayName": "Olaf",
    "descShort": "OMNITRACKER-Fachexperte der Pommer Consulting",
    "wertstrom": "20-service-to-cash",
    "customerFacing": false,
    "tags": [
      "omnitracker",
      "bpmn",
      "com-automation",
      "internal"
    ],
    "avatarUrl": "/personas/ot-expert-default.webp"
  },
  {
    "key": "prisca",
    "displayName": "Prisca",
    "descShort": "Quality-Gate-Reviewerin der Pommer Agent Firm",
    "wertstrom": "99-querschnitt",
    "customerFacing": false,
    "tags": [
      "quality-gate",
      "reviewer",
      "itil",
      "compliance",
      "internal"
    ],
    "avatarUrl": "/personas/prisca-default.webp"
  },
  {
    "key": "ulli",
    "displayName": "Ulli",
    "descShort": "Quality-Gate-Reviewerin der Pommer Agent Firm",
    "wertstrom": "99-querschnitt",
    "customerFacing": false,
    "tags": [
      "quality-gate",
      "reviewer",
      "end-user",
      "readability",
      "internal"
    ],
    "avatarUrl": "/personas/ulli-default.webp"
  },
  {
    "key": "valerie",
    "displayName": "Valerie",
    "descShort": "Quality-Gate-Reviewerin der Pommer Agent Firm",
    "wertstrom": "99-querschnitt",
    "customerFacing": false,
    "tags": [
      "quality-gate",
      "reviewer",
      "ot-admin",
      "internal"
    ],
    "avatarUrl": "/personas/valerie-default.webp"
  }
];
